version: "3.5"
services:
    sql-serve-db:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - "1533:1433" # Ánh xạ từ port 1433 mặc định sang port 1533, 1433 là port của sql, 1533 là port mà máy tính có thể truy cập
        environment:
            SA_PASSWORD: "Password@123"
            ACCEPT_EULA: "Y"